Repository laminas/laminas-mvc, pull requests merged in 2022-08, with the labels that each got.

#103 First draft of the modules doc
  docs/book/modules.md
Labels: Documentation, Enhancement

#123 Drop ModuleRouteListener support
  docs/book/mvc-event.md
  src/Controller/Plugin/Url.php
  src/ModuleRouteListener.php
  test/Controller/Plugin/UrlTest.php
  test/ModuleRouteListenerTest.php
  test/View/InjectTemplateListenerTest.php
Labels: BC Break, Feature Removal, RFC

#122 Apply PHP 7.4 syntax and typed property
  psalm-baseline.xml
  src/Application.php
  src/ConfigProvider.php
  src/Controller/AbstractController.php
  src/DispatchListener.php
  src/Service/ViewHelperManagerFactory.php
  test/Application/AllowsReturningEarlyFromRoutingTest.php
  test/Application/BadControllerTrait.php
  test/Application/ExceptionsRaisedInDispatchableShouldRaiseDispatchErrorEventTest.php
  test/Application/InabilityToRetrieveControllerShouldTriggerDispatchErrorTest.php
  test/Application/InabilityToRetrieveControllerShouldTriggerExceptionTest.php
  test/Application/InvalidControllerTypeShouldTriggerDispatchErrorTest.php
  test/Application/InvalidControllerTypeTrait.php
  test/Application/MissingControllerTrait.php
  test/Application/PathControllerTrait.php
  test/Application/RoutingSuccessTest.php
  test/ApplicationTest.php
  test/Controller/ActionControllerTest.php
  test/Controller/ControllerManagerTest.php
  test/Controller/IntegrationTest.php
  test/Controller/Plugin/ForwardTest.php
  test/Controller/RestfulControllerTest.php
  test/DispatchListenerTest.php
  test/ResponseSender/PhpEnvironmentResponseSenderTest.php
  test/SendResponseListenerTest.php
  test/Service/ViewFeedStrategyFactoryTest.php
  test/Service/ViewHelperManagerFactoryTest.php
  test/Service/ViewJsonStrategyFactoryTest.php
  test/Service/ViewManagerFactoryTest.php
  test/View/DefaultRenderingStrategyTest.php
  test/View/RouteNotFoundStrategyTest.php
Labels: Enhancement
