Repository laminas/laminas-mvc, pull requests merged in 2022-02, with the labels that each got.

#95 Fully clean up quick start
  docs/book/quick-start.md
Labels: Documentation

#96 Add `ControllerManager::class` as resolvable service
  src/Service/ServiceListenerFactory.php
  test/Application/InvalidControllerTypeTrait.php
  test/ApplicationTest.php
Labels: Enhancement

#100 Bugfix: Revert changing canonical name of `ControllerManager` service
  src/Service/ServiceListenerFactory.php
  test/Application/BadControllerTrait.php
  test/Application/InvalidControllerTypeTrait.php
  test/Application/PathControllerTrait.php
  test/ApplicationTest.php
Labels: Bug

#98 Improve Routing docs
  docs/book/routing.md
Labels: Documentation, Enhancement

#107 Update `quick-start.md` to fix typo in `composer create-project` command
  docs/book/quick-start.md
Labels: Bug, Documentation

#104 Prepare for Renovate with reusable workflows
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  composer.json
Labels: Enhancement
