Repository laminas/laminas-mvc, pull requests merged in 2024-11, with the labels that each got.

#174 Add support for PHP 8.4, Upgrade PHPUnit to 10.x, remove Prophecy dependency and improve unit tests
  .laminas-ci.json
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Controller/AbstractController.php
  src/Controller/AbstractRestfulController.php
  src/Controller/LazyControllerAbstractFactory.php
  src/Controller/Plugin/AcceptableViewModelSelector.php
  src/Controller/Plugin/Forward.php
  src/Controller/Plugin/Service/ForwardFactory.php
  src/Controller/PluginManager.php
  src/ResponseSender/AbstractResponseSender.php
  src/Service/ConfigFactory.php
  src/Service/ViewFeedStrategyFactory.php
  src/Service/ViewJsonStrategyFactory.php
  test/Application/InvalidControllerTypeShouldTriggerDispatchErrorTest.php
  test/Application/TestAsset/modules/Application/src/Application/Controller/PathController.php
  test/ApplicationTest.php
  test/Controller/LazyControllerAbstractFactoryTest.php
  test/Controller/Plugin/TestAsset/SamplePluginFactory.php
  test/Controller/Plugin/TestAsset/SamplePluginWithConstructorFactory.php
  test/Controller/RestfulControllerTest.php
  test/Controller/TestAsset/ControllerLoaderAbstractFactory.php
  test/Controller/TestAsset/ControllerWithMixedConstructorParameters.php
  test/Controller/TestAsset/UneventfulController.php
  test/Controller/TestAsset/UnlocatableControllerLoaderAbstractFactory.php
  test/Controller/TestAsset/UnlocatableEventfulController.php
  test/DispatchListenerTest.php
  test/ResponseSender/AbstractResponseSenderTest.php
  test/ResponseSender/PhpEnvironmentResponseSenderTest.php
  test/ResponseSender/SimpleStreamResponseSenderTest.php
  test/SendResponseListenerTest.php
  test/Service/HttpMethodListenerFactoryTest.php
  test/Service/InjectTemplateListenerFactoryTest.php
  test/Service/RequestFactoryTest.php
  test/Service/ResponseFactoryTest.php
  test/Service/SendResponseListenerFactoryTest.php
  test/Service/ServiceListenerFactoryTest.php
  test/Service/ServiceManagerConfigTest.php
  test/Service/TestAsset/ControllerWithDependencies.php
  test/Service/ViewFeedStrategyFactoryTest.php
  test/Service/ViewHelperManagerFactoryTest.php
  test/Service/ViewJsonStrategyFactoryTest.php
  test/Service/ViewManagerFactoryTest.php
  test/Service/ViewPrefixPathStackResolverFactoryTest.php
  test/TestAsset/Locator.php
  test/TestAsset/MiddlewareAbstractFactory.php
  test/TestAsset/PathController.php
  test/View/CreateViewModelListenerTest.php
  test/View/RouteNotFoundStrategyTest.php
Labels: Enhancement, dependencies, QA

#173 Update to latest PHP 8.1 syntax
  src/Application.php
  src/Controller/AbstractController.php
  src/Controller/MiddlewareController.php
  src/Controller/Plugin/AcceptableViewModelSelector.php
  src/Controller/Plugin/Forward.php
  src/DispatchListener.php
  src/SendResponseListener.php
  src/Service/ModuleManagerFactory.php
  src/Service/ServiceListenerFactory.php
  src/View/Http/InjectTemplateListener.php
  src/View/Http/ViewManager.php
  test/Application/InitializationIntegrationTest.php
  test/Controller/Plugin/ForwardTest.php
  test/Service/ViewHelperManagerFactoryTest.php
Labels: Enhancement, QA

#178 Removed abandoned laminas-json
  composer.json
  src/Controller/AbstractRestfulController.php
Labels: Enhancement, dependencies
